export const FETCH_STORE         = 'FETCH_STORE'
export const FETCH_STORE_SUCCESS = 'FETCH_STORE_SUCCESS'
export const FETCH_STORE_FAILURE = 'FETCH_STORE_FAILURE'
export const END_FETCH_STORE     = 'END_FETCH_STORE'
export const DESTROY_FETCH_STORE = 'DESTROY_FETCH_STORE'

export const FETCH_CART     = 'FETCH_CART'
export const FETCH_ALL_CART = 'FETCH_ALL_CART'
export const ADD_CART       = 'ADD_CART'
export const MINUS_CART     = 'MINUS_CART'
export const DESTROY_CART   = 'DESTROY_CART'
export const UPDATE_CART    = 'UPDATE_CART'
export const OPEN_CHECKOUT  = 'OPEN_CHECKOUT'
export const CLOSE_CHECKOUT = 'CLOSE_CHECKOUT'